name = 'vivid vista'
license = 'MIT'
licenselink = ''
description = 'Portfolio blogging site built with Hugo and Tailwind CSS'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/namwa/vivid-vista'

# Taxonomy terms
tags = ['blog', 'portfolio', 'static site', 'tailwind css']
features = ['maximalism', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Namwa Sawasdiworn'
  homepage = 'https://www.namwa.dev'
